### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by Joel18241096** [NZqian/RapBank#1]
thank you for your excellent work! Do you have any plan for code release? thx :)

**Comment by NZqian** [comment]
sorry for the late reply. The dataset and the processing pipeline is released, but we are not planning to open-source the code for the model. However, I think it's not difficult to adapt our approach to other open-sourced model (e.g. CosyVoice, which has a similar architecture).

**Comment by Joel18241096** [comment]
> sorry for the late reply. The dataset and the processing pipeline is released, but we are not planning to open-source the code for the model. However, I think it's not difficult to adapt our approach to other open-sourced model (e.g. CosyVoice, which has a similar architecture).

Got it. Thank you again for your work :)

**Comment by Joel18241096** [comment]
> sorry for the late reply. The dataset and the processing pipeline is released, but we are not planning to open-source the code for the model. However, I think it's not difficult to adapt our approach to other open-sourced model (e.g. CosyVoice, which has a similar architecture).

Got it. Thank you again for your work. 👍 :)
