### ISSUE TITLE
Is there anyone who can replicate this paper?

### ISSUE THREAD

**Issue by mkygogo** [NZqian/RapBank#2]
They probably won't open source the model. Is there anyone who can replicate their paper?
https://arxiv.org/abs/2408.15474

**Comment by leonqiu2012** [comment]
It seems all the source code is in the repo, but there is almost no explanation about how to use these scripts. You may need to read the paper and figure out how to use them.

**Comment by EobardThawne721** [comment]
> It seems all the source code is in the repo, but there is almost no explanation about how to use these scripts. You may need to read the paper and figure out how to use them.

hi，leonqiu . I saw in the original paper that in the first stage, a  language model was used from lyrics to semantics. What is this type of language model, or is there a simple example? Because I am curious about how these audio and semantic features are input into the large model for prediction. I am looking forward to your  reply at your earlist

**Comment by NZqian** [comment]
> It seems all the source code is in the repo, but there is almost no explanation about how to use these scripts. You may need to read the paper and figure out how to use them.

This repo only contains the dataset and the data processing pipeline. If you have any questions about the pipeline, feel free to ask!

**Comment by NZqian** [comment]
> > It seems all the source code is in the repo, but there is almost no explanation about how to use these scripts. You may need to read the paper and figure out how to use them.
> 
> hi，leonqiu . I saw in the original paper that in the first stage, a language model was used from lyrics to semantics. What is this type of language model, or is there a simple example? Because I am curious about how these audio and semantic features are input into the large model for prediction. I am looking forward to your reply at your earlist

The LM is llama, implemented using Transformers: https://github.com/huggingface/transformers/blob/4e27a4009d3f9d4e44e9be742e8cd742daf074f4/src/transformers/models/llama/modeling_llama.py#L751

**Comment by EobardThawne721** [comment]
> > > It seems all the source code is in the repo, but there is almost no explanation about how to use these scripts. You may need to read the paper and figure out how to use them.
> > 
> > 
> > hi，leonqiu . I saw in the original paper that in the first stage, a language model was used from lyrics to semantics. What is this type of language model, or is there a simple example? Because I am curious about how these audio and semantic features are input into the large model for prediction. I am looking forward to your reply at your earlist
> 
> The LM is llama, implemented using Transformers: https://github.com/huggingface/transformers/blob/4e27a4009d3f9d4e44e9be742e8cd742daf074f4/src/transformers/models/llama/modeling_llama.py#L751

Thank you for your reply, so am I using this frozen pre trained model directly? I'm actually quite confused about how to input audio features and text features to predict and output results

**Comment by NZqian** [comment]
> > > > It seems all the source code is in the repo, but there is almost no explanation about how to use these scripts. You may need to read the paper and figure out how to use them.
> > > 
> > > 
> > > hi，leonqiu . I saw in the original paper that in the first stage, a language model was used from lyrics to semantics. What is this type of language model, or is there a simple example? Because I am curious about how these audio and semantic features are input into the large model for prediction. I am looking forward to your reply at your earlist
> > 
> > 
> > The LM is llama, implemented using Transformers: https://github.com/huggingface/transformers/blob/4e27a4009d3f9d4e44e9be742e8cd742daf074f4/src/transformers/models/llama/modeling_llama.py#L751
> 
> Thank you for your reply, so am I using this frozen pre trained model directly? I'm actually quite confused about how to input audio features and text features to predict and output results

The model configuration can be found in the appendix of the paper. The LM does not operates on pure text, so you cannot just use any frozen nlp models. The LM should be traind from scrach. The input are continous embeddings, and the output are discrete tokens.

**Comment by EobardThawne721** [comment]
> > > > > It seems all the source code is in the repo, but there is almost no explanation about how to use these scripts. You may need to read the paper and figure out how to use them.
> > > > 
> > > > 
> > > > hi，leonqiu . I saw in the original paper that in the first stage, a language model was used from lyrics to semantics. What is this type of language model, or is there a simple example? Because I am curious about how these audio and semantic features are input into the large model for prediction. I am looking forward to your reply at your earlist
> > > 
> > > 
> > > The LM is llama, implemented using Transformers: https://github.com/huggingface/transformers/blob/4e27a4009d3f9d4e44e9be742e8cd742daf074f4/src/transformers/models/llama/modeling_llama.py#L751
> > 
> > 
> > Thank you for your reply, so am I using this frozen pre trained model directly? I'm actually quite confused about how to input audio features and text features to predict and output results
> 
> The model configuration can be found in the appendix of the paper. The LM does not operates on pure text, so you cannot just use any frozen nlp models. The LM should be traind from scrach. The input are continous embeddings, and the output are discrete tokens.

I am truly grateful to you! Your answer has solved my confusion because I am a rookie. The papers I have read before used frozen LM to input audio and text features, but I just don't know how they are implemented. Your answer has been very helpful to me!
