### ISSUE TITLE
 what is the lm of Stage 1:lyrics to semantics 

### ISSUE THREAD

**Issue by EobardThawne721** [NZqian/RapBank#3]
Firstly, I would like to express my gratitude to the author for your contributions and the code provided.
I have read your paper and I am very interested in the first stage of your paper. Does the transformer decoder used in the paper usually directly use the pre trained LM decoder part? If so, can you roughly explain it? As a rookie, I am confused about how to connect audio features and text features and send them in transformer decoder.
Or is it the code for the transformer decoder that you wrote yourself

**Comment by NZqian** [comment]
> Firstly, I would like to express my gratitude to the author for your contributions and the code provided. I have read your paper and I am very interested in the first stage of your paper. Does the transformer decoder used in the paper usually directly use the pre trained LM decoder part? If so, can you roughly explain it? As a rookie, I am confused about how to connect audio features and text features and send them in transformer decoder. Or is it the code for the transformer decoder that you wrote yourself

Thank you for your interest in our work！
The implementation of the LM is taken from Transformers and is trained from scrach: https://github.com/huggingface/transformers/blob/4e27a4009d3f9d4e44e9be742e8cd742daf074f4/src/transformers/models/llama/modeling_llama.py#L751
The lyrics tokens and the semantic tokens are first concatenated along the time axis, then embedded to get the continous embedded feature. Then the accompaniment feature is added to the continous feature with the "K-frames-shift" strategy.

**Comment by Clarksvia** [comment]
> > Firstly, I would like to express my gratitude to the author for your contributions and the code provided. I have read your paper and I am very interested in the first stage of your paper. Does the transformer decoder used in the paper usually directly use the pre trained LM decoder part? If so, can you roughly explain it? As a rookie, I am confused about how to connect audio features and text features and send them in transformer decoder. Or is it the code for the transformer decoder that you wrote yourself
> 
> Thank you for your interest in our work！ The implementation of the LM is taken from Transformers and is trained from scrach: https://github.com/huggingface/transformers/blob/4e27a4009d3f9d4e44e9be742e8cd742daf074f4/src/transformers/models/llama/modeling_llama.py#L751 The lyrics tokens and the semantic tokens are first concatenated along the time axis, then embedded to get the continous embedded feature. Then the accompaniment feature is added to the continous feature with the "K-frames-shift" strategy.

I would like to express my gratitude to the author for your contributions and the code provided！I have read your paper and I am very interested in your paper. I'm curious if the phrase “The lyrics tokens and the semantic tokens are first concatenated along the time axis, then embedded to get the continuous embedded feature. Then the accompaniment feature is added to the continuous feature with the "K-frames-shift" strategy.“ means the following: Assuming the lyrics and semantic tokens are concatenated and embedded to become a (l+n,d) of continuous embedded feature, and the accompaniment feature has the same length as the semantic tokens, which is (n,d), does shifting the accompaniment feature by K mean adding it to the values in the range [l-k: l+n-k] of the continuous embedded feature?
